server:
  servlet:
    context-path: /phoneBook-api
  port: 8081
  
spring:
  datasource:
    url: jdbc:mysql://localhost/phone_book?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate.ddl-auto: validate
    generate-ddl: true
    show-sql: true
